services:
  db:
    image: postgres:18.0-trixie
    container_name: postgres_db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'